### PR TITLE
fix(utils): escape % character in passwords

### PR DESCRIPTION
**Pull request by mmvanheusden**
This is very shitty code and there are probably many other edge cases that have this problem.
I will delve deeper in this issue and hopefully can be able to fully fix it in the upcoming rewrite.

@sudo-Juergens, Could you test this? I will attach a binary

### CODE REVIEW

**Comment by mmvanheusden** [comment]
https://filetransfer.kpn.com/download/50312dcf-7e7f-44cf-bd00-7e80ca23b0ed#azQcsRHTICxqpmnkVExPwDeeQl5m86ii4wiimqRme04.

**Comment by berhox** [comment]
@mmvanheusden This does work. However, as you say, its not very elegant.

**Review by berhox — APPROVED** [review]
The code works and fixes the bug.

**Comment by mmvanheusden** [comment]
Amazing! I will bring out a patch

**Pull request merged**
