### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by TechDevOfficial**

### CODE REVIEW

**Comment by mmvanheusden** [comment]
nice

**Comment by Bluscream** [comment]
Lmao. Can we dmca his fork?

**Comment by TechDevOfficial** [comment]
What do you mean?

**Comment by TechDevOfficial** [comment]
Should I delete the fork?

**Comment by mmvanheusden** [comment]
> Should I delete the fork?

Noo, do what you desire😉

**Comment by TechDevOfficial** [comment]
so can I keep it?

**Comment by mmvanheusden** [comment]
> so can I keep it?

Yes, this is the magic of open-source :)

**Comment by TechDevOfficial** [comment]
"dmca" it's Digital Millennium Copyright Act, so i thinked that i should have to delete it.

**Comment by mmvanheusden** [comment]
> "dmca" it's Digital Millennium Copyright Act, so i thinked that i should have to delete it.

he isn't serious

as long as you follow the project's license, gnu gpl3, everything is good.

**Comment by TechDevOfficial** [comment]
Okk

**Pull request closed without merging**
